FROM node:22.14.0-alpine3.21@sha256:9bef0ef1e268f60627da9ba7d7605e8831d5b56ad07487d24d1aa386336d1944 AS dependencies
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9.10.0 --activate
COPY packages/studio/package.json packages/studio/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-workspace

FROM node:22.14.0-alpine3.21@sha256:9bef0ef1e268f60627da9ba7d7605e8831d5b56ad07487d24d1aa386336d1944
WORKDIR /app
ENV NODE_ENV=production
COPY --from=dependencies --chown=node:node /app/node_modules ./node_modules
COPY --chown=node:node packages/studio/ ./
USER node
EXPOSE 4178
CMD ["node", "server/index.mjs"]
