// A interface do Puck em português. As chaves são as do dicionário em inglês do próprio
// pacote (@puckeditor/core 0.23); a que faltar aparece em inglês.
export const dicionario = {
  'header-publish': 'Salvar',
  'header-undo': 'desfazer',
  'header-redo': 'refazer',
  'header-toggle-leftsidebar': 'Mostrar ou esconder o painel da esquerda',
  'header-toggle-rightsidebar': 'Mostrar ou esconder o painel da direita',
  'header-toggle-menubar': 'Mostrar ou esconder o menu',
  'action-selectparent': 'Selecionar o bloco de fora',
  'action-duplicate': 'Duplicar',
  'action-delete': 'Excluir',
  'label-page': 'Página',
  'label-component': 'Bloco',
  'outline-empty': 'Nenhum bloco',
  'outline-item-collapse': 'Recolher',
  'outline-item-expand': 'Expandir',
  'outline-header-title': 'Estrutura',
  'outline-header-collapseall': 'Recolher tudo',
  'outline-item-duplicate': 'Duplicar',
  'outline-item-delete': 'Excluir',
  'drawer-category-collapse': 'Recolher {title}',
  'drawer-category-expand': 'Expandir {title}',
  'drawer-category-other': 'Outros',
  'canvas-noconfig': 'Sem configuração para {type}',
  'field-readonly': 'Somente leitura',
  'field-arrayitem-summary': 'Item {index}',
  'field-arrayitem-duplicate': 'Duplicar',
  'field-arrayitem-delete': 'Excluir',
  'field-external-selectdata': 'Escolher',
  'field-external-search': 'Buscar',
  'field-external-togglefilters': 'Mostrar ou esconder filtros',
  'field-external-item': 'Item',
  'field-external-result-singular': '{count} resultado',
  'field-external-result-plural': '{count} resultados',
  'viewport-zoom-in': 'Aproximar',
  'viewport-zoom-out': 'Afastar',
  'viewport-zoom-auto': '{zoom}%',
  'viewport-toggle-menu': 'Escolher a largura da tela',
  'viewport-switch': 'Ver como {label}',
  'viewport-switch-default': 'Trocar a largura da tela',
  'plugin-blocks': 'Blocos',
  'plugin-outline': 'Estrutura',
  'plugin-fields': 'Propriedades',
  'plugin-components': 'Blocos',
  'layout-maximize': 'maximizar',
  'layout-minimize': 'minimizar',
  'loader-loading': 'carregando',
};

export const larguras = [
  { width: 390, height: 'auto', label: 'celular', icon: 'Smartphone' },
  { width: 768, height: 'auto', label: 'tablet', icon: 'Tablet' },
  { width: 1440, height: 'auto', label: 'computador', icon: 'Monitor' },
];
